apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: github-runner
        image: docker.pkg.github.com/mifonpe/github-runner/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: mifonpe
        - name: GITHUB_REPOSITORY
          value: alteos-microservice
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        volumeMounts:
        - mountPath: /home/github/_work
          name: workspace
      volumes:
      - name: workspace
        emptyDir: {}
